stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-adoptopenjdk-11
      shellScript: mvn package -DskipTests
- name: Build Docker with DIND
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: docker.dev.folio.org/mod-pubsub:vega-${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: docker.dev.folio.org
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: p-jqjbc:vega-helmcharts-mod-pubsub
      version: 0.1.32
      answers:
        image.repository: docker.dev.folio.org/mod-pubsub
        image.tag: vega-${CICD_EXECUTION_SEQUENCE}
      targetNamespace: vega
      name: mod-pubsub
timeout: 60
notification: {}
